# Generated by Django 4.1.7 on 2023-03-18 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tgusers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tguser_id', models.CharField(max_length=20)),
                ('users_name', models.CharField(max_length=100)),
            ],
        ),
    ]
