# Generated by Django 4.1.7 on 2023-03-19 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0002_dumbbuttonpressed_fatbuttonpressed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ButtonsPressed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stupid_btn_counter', models.IntegerField(default=0)),
                ('dumb_btn_counter', models.IntegerField(default=0)),
                ('fat_btn_counter', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='DumbButtonPressed',
        ),
        migrations.DeleteModel(
            name='FatButtonPressed',
        ),
        migrations.DeleteModel(
            name='StupidButtonPressed',
        ),
    ]
