# Generated by Django 4.1.7 on 2023-03-20 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0003_buttonspressed_delete_dumbbuttonpressed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stupid_btn_counter', models.IntegerField(default=0)),
                ('dumb_btn_counter', models.IntegerField(default=0)),
                ('fat_btn_counter', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ButtonsPressed',
        ),
    ]
