# Generated by Django 4.1.7 on 2023-03-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0004_button_delete_buttonspressed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tgusers',
            name='id',
        ),
        migrations.AlterField(
            model_name='tgusers',
            name='tguser_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
