# Generated by Django 4.1.7 on 2023-03-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgbot', '0007_alter_tgusers_tguser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tgusers',
            name='tguser_id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
